name: Markdown Lint

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run markdownlint
        uses: docker://davidanson/markdownlint-cli2
        with:
          args: "_posts/*.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}